### PR TITLE
Update regex

### PR DESCRIPTION
**Pull request by rsevilla87**
Update regex to match current installer log

### CODE REVIEW

**Comment by aakarshg** [comment]
Which version of OCP is this valid for ? @rsevilla87

**Comment by rsevilla87** [comment]
It worked for me in 4.4. The new regex should work with every version since it matches every integer number rather than a fixed number of minutes.
In the other hand, we no longer require this in recent versions since the installer now reports these numbers to stdout according to https://github.com/openshift/installer/pull/3263
cc: @chaitanyaenr @jtaleric

**Review by jtaleric — APPROVED** [review]
LGTM - Hopefully after moving to 4.5 we won't need this anymore. 
New format from the installer :
```
time="2020-05-01T15:29:03Z" level=debug msg="Time elapsed per stage:"
time="2020-05-01T15:29:03Z" level=debug msg="    Infrastructure: 5m26s"
time="2020-05-01T15:29:03Z" level=debug msg="Bootstrap Complete: 11m23s"
time="2020-05-01T15:29:03Z" level=debug msg="               API: 42s"
time="2020-05-01T15:29:03Z" level=debug msg=" Bootstrap Destroy: 51s"
time="2020-05-01T15:29:03Z" level=debug msg=" Cluster Operators: 11m24s"
time="2020-05-01T15:29:03Z" level=info msg="Time elapsed: 29m11s"
```

**Review by chaitanyaenr — APPROVED** [review]
LGTM

**Pull request merged**
